@load ./bash-cve-2014-6271.bro
@load ./bitcoin
@load ./dataloss
@load ./exploitkit.bro
@load ./largeUpload.bro
@load ./meterpreter.bro
@load ./persistent_talkers.bro
@load ./scan_udp.bro
@load ./covert_tcp_steganalysis
@load ./icmpvariance
